# Generated by Django 6.0.2 on 2026-03-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='faculty',
        ),
    ]
