# Generated by Django 6.0.2 on 2026-03-08 16:06

import django.db.models.deletion
from django.db import migrations, models


def set_default_organization(apps, schema_editor):
    Semester = apps.get_model('core', 'Semester')
    Organization = apps.get_model('core', 'Organization')
    
    # Try to find a UNION_SCHOOL organization
    school = Organization.objects.filter(type='UNION_SCHOOL').first()
    
    if school:
        Semester.objects.filter(organization__isnull=True).update(organization=school)

def reverse_default_organization(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_phase5_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.organization'),
        ),
        migrations.RunPython(set_default_organization, reverse_default_organization),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('organization',), name='unique_current_semester_per_school'),
        ),
    ]
