# Generated by Django 6.0.2 on 2026-03-08 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_point_category_with_org'),
        ('attendance', '0006_remove_activitypoint_unique_student_activity_point_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_student_code', models.CharField(blank=True, max_length=20, null=True)),
                ('entered_student_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Đã đăng ký'), ('ATTENDED', 'Đã tham gia (Chờ duyệt)'), ('VERIFIED', 'Đã duyệt tham gia'), ('ABSENT', 'Vắng mặt'), ('CANCELED', 'Đã hủy'), ('BANNED', 'Bị cấm')], default='REGISTERED', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('awarded_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tham gia hoạt động',
                'verbose_name_plural': 'Tham gia hoạt động',
                'db_table': 'activity_participations',
            },
        ),
        migrations.RemoveConstraint(
            model_name='activityregistration',
            name='unique_activity_registration',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='task',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='activity',
            name='budget_info',
            field=models.JSONField(blank=True, default=dict, help_text='Tổng hợp dự trù kinh phí', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='tasks_info',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách task công việc', null=True),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='attendance_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='point_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_participations', to='activities.pointcategory'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='activityregistration',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityregistration',
            name='student',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='BudgetItem',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddConstraint(
            model_name='activityparticipation',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('activity', 'student'), name='unique_activity_student_participation'),
        ),
        migrations.DeleteModel(
            name='ActivityRegistration',
        ),
    ]
