# Generated by Django 6.0.2 on 2026-03-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_add_point_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Số điểm rèn luyện nhận được khi hoàn thành hoạt động', max_digits=5),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Đã đăng ký'), ('CANCELED', 'Đã hủy'), ('BANNED', 'Bị cấm'), ('ATTENDED', 'Đã tham gia'), ('POINT_AWARDED', 'Đã cộng điểm')], default='REGISTERED', max_length=20),
        ),
    ]
