# Generated by Django 6.0.2 on 2026-03-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activityparticipation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipation',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Đã đăng ký'), ('ATTENDED', 'Đã tham gia (Chờ duyệt)'), ('VERIFIED', 'Đã duyệt tham gia'), ('REJECTED', 'Từ chối'), ('CANCELED', 'Đã hủy'), ('BANNED', 'Bị cấm')], default='REGISTERED', max_length=20),
        ),
    ]
