# Generated by Django 6.0.2 on 2026-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_phase1_points_and_schema_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Giới hạn số lượng sinh viên đăng ký. Để trống nếu không giới hạn.', null=True),
        ),
    ]
