# Generated by Django 6.0.2 on 2026-03-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activityparticipation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='tasks_info',
        ),
    ]
