-- =============================================================================
-- YouthHub — PostgreSQL Schema
-- Updated: 2026-03-03
-- Synchronized with Django models (Phase 1–5)
-- =============================================================================

-- ── Custom Enum Types ─────────────────────────────────────────────────────────
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('ADMIN', 'STAFF', 'STUDENT');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_status') THEN
        CREATE TYPE user_status AS ENUM ('ACTIVE', 'LOCKED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'org_type') THEN
        CREATE TYPE org_type AS ENUM ('UNION_SCHOOL', 'UNION_FACULTY', 'CLASS', 'CLUB');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_type') THEN
        CREATE TYPE activity_type AS ENUM ('VOLUNTEER', 'MEETING', 'ACADEMIC', 'OTHER');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_status') THEN
        CREATE TYPE activity_status AS ENUM ('DRAFT', 'PENDING', 'APPROVED', 'ONGOING', 'DONE', 'CANCELED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reg_status') THEN
        CREATE TYPE reg_status AS ENUM ('REGISTERED', 'CANCELED', 'BANNED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'session_status') THEN
        CREATE TYPE session_status AS ENUM ('OPEN', 'CLOSED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'record_status') THEN
        CREATE TYPE record_status AS ENUM ('PENDING', 'VERIFIED', 'REJECTED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'doc_type') THEN
        CREATE TYPE doc_type AS ENUM ('PLAN', 'REPORT', 'INVITATION', 'OTHER');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ai_status') THEN
        CREATE TYPE ai_status AS ENUM ('RAW', 'DRAFT', 'EDITED', 'FINAL');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'budget_status') THEN
        CREATE TYPE budget_status AS ENUM ('DRAFT', 'APPROVED', 'REJECTED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_status') THEN
        CREATE TYPE task_status AS ENUM ('TODO', 'IN_PROGRESS', 'DONE');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'audit_action') THEN
        CREATE TYPE audit_action AS ENUM ('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'REJECT', 'LOGIN', 'LOGOUT');
    END IF;
END $$;

-- =============================================================================
-- 1. users
-- =============================================================================
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(150)  NOT NULL UNIQUE,
    password        VARCHAR(128)  NOT NULL,
    full_name       VARCHAR(255)  NOT NULL,
    email           VARCHAR(254)  NOT NULL UNIQUE,
    phone           VARCHAR(15)   NULL,
    role            user_role     NOT NULL DEFAULT 'STUDENT',
    avatar_url      VARCHAR(500)  NULL,
    status          user_status   NOT NULL DEFAULT 'ACTIVE',
    -- Django auth fields
    is_staff        BOOLEAN       NOT NULL DEFAULT FALSE,
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
    is_superuser    BOOLEAN       NOT NULL DEFAULT FALSE,
    last_login      TIMESTAMPTZ   NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 2. student_profiles
-- =============================================================================
CREATE TABLE IF NOT EXISTS student_profiles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL UNIQUE,
    student_code    VARCHAR(20)   NOT NULL UNIQUE,
    faculty         VARCHAR(100)  NOT NULL,
    class_name      VARCHAR(50)   NULL,
    course_year     VARCHAR(20)   NULL,
    CONSTRAINT fk_student_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =============================================================================
-- 3. organizations
-- =============================================================================
CREATE TABLE IF NOT EXISTS organizations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id       BIGINT        NULL,
    type            org_type      NOT NULL,
    name            VARCHAR(255)  NOT NULL,
    code            VARCHAR(50)   NOT NULL UNIQUE,
    description     TEXT          NULL,
    status          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_org_parent FOREIGN KEY (parent_id) REFERENCES organizations(id) ON DELETE SET NULL
);

-- =============================================================================
-- 4. organization_members
-- =============================================================================
CREATE TABLE IF NOT EXISTS organization_members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT        NOT NULL,
    user_id         BIGINT        NOT NULL,
    position        VARCHAR(100)  NOT NULL,
    is_officer      BOOLEAN       NOT NULL DEFAULT FALSE,
    joined_at       DATE          NOT NULL,
    left_at         DATE          NULL,
    CONSTRAINT fk_member_org  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_member_user FOREIGN KEY (user_id)         REFERENCES users(id)        ON DELETE CASCADE,
    CONSTRAINT uq_org_user UNIQUE (organization_id, user_id)
);

-- =============================================================================
-- 5. semesters
-- =============================================================================
CREATE TABLE IF NOT EXISTS semesters (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)  NOT NULL,
    academic_year   VARCHAR(20)   NOT NULL,
    start_date      DATE          NOT NULL,
    end_date        DATE          NOT NULL,
    is_current      BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_semester_dates CHECK (start_date < end_date)
);

-- =============================================================================
-- 6. point_categories  [Phase 3 — Added]
-- =============================================================================
CREATE TABLE IF NOT EXISTS point_categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)  NOT NULL,
    code            VARCHAR(50)   NOT NULL UNIQUE,
    description     TEXT          NULL,
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 7. activities
-- =============================================================================
CREATE TABLE IF NOT EXISTS activities (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id     BIGINT          NOT NULL,
    semester_id         BIGINT          NULL,
    point_category_id   BIGINT          NULL,  -- FK to point_categories
    title               VARCHAR(255)    NOT NULL,
    code                VARCHAR(50)     NOT NULL UNIQUE,
    description         TEXT            NULL,
    activity_type       activity_type   NOT NULL,
    start_time          TIMESTAMPTZ     NOT NULL,
    end_time            TIMESTAMPTZ     NOT NULL,
    location            VARCHAR(255)    NOT NULL,
    status              activity_status NOT NULL DEFAULT 'DRAFT',
    created_by          BIGINT          NOT NULL,
    approved_by         BIGINT          NULL,
    approved_at         TIMESTAMPTZ     NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_org        FOREIGN KEY (organization_id)   REFERENCES organizations(id),
    CONSTRAINT fk_activity_semester   FOREIGN KEY (semester_id)       REFERENCES semesters(id)         ON DELETE SET NULL,
    CONSTRAINT fk_activity_point_cat  FOREIGN KEY (point_category_id) REFERENCES point_categories(id)  ON DELETE SET NULL,
    CONSTRAINT fk_activity_creator    FOREIGN KEY (created_by)        REFERENCES users(id),
    CONSTRAINT fk_activity_approver   FOREIGN KEY (approved_by)       REFERENCES users(id)             ON DELETE SET NULL
);

-- =============================================================================
-- 12. attendance_sessions
-- =============================================================================
CREATE TABLE IF NOT EXISTS attendance_sessions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id     BIGINT          NOT NULL,
    name            VARCHAR(100)    NOT NULL,
    start_time      TIMESTAMPTZ     NOT NULL,
    end_time        TIMESTAMPTZ     NOT NULL,
    qr_token        VARCHAR(255)    NOT NULL UNIQUE,
    requires_photo  BOOLEAN         NOT NULL DEFAULT FALSE,
    status          session_status  NOT NULL DEFAULT 'OPEN',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_session_activity FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE
);

-- =============================================================================
CREATE TABLE IF NOT EXISTS attendance_records (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_session_id   BIGINT          NOT NULL,
    activity_id             BIGINT          NULL,  -- Denormalized for quick query
    student_id              BIGINT          NULL,
    entered_student_code    VARCHAR(20)     NOT NULL,
    checkin_time            TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    photo_path              VARCHAR(500)    NULL,
    verified_by             BIGINT          NULL,
    status                  record_status   NOT NULL DEFAULT 'PENDING',
    approved_at             TIMESTAMPTZ     NULL,
    CONSTRAINT fk_record_session  FOREIGN KEY (attendance_session_id) REFERENCES attendance_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_record_activity FOREIGN KEY (activity_id)           REFERENCES activities(id)          ON DELETE CASCADE,
    CONSTRAINT fk_record_student  FOREIGN KEY (student_id)            REFERENCES users(id)               ON DELETE SET NULL,
    CONSTRAINT fk_record_verifier FOREIGN KEY (verified_by)           REFERENCES users(id)               ON DELETE SET NULL
);
-- Partial unique index: 1 student per session (guests allowed to check in multiple times)
CREATE UNIQUE INDEX IF NOT EXISTS uq_session_student
    ON attendance_records (attendance_session_id, student_id)
    WHERE student_id IS NOT NULL;

-- =============================================================================
CREATE TABLE IF NOT EXISTS activity_points (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT          NOT NULL,
    activity_id     BIGINT          NOT NULL,
    points          DECIMAL(5,2)    NOT NULL,
    reason          VARCHAR(255)    NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_point_student  FOREIGN KEY (student_id)  REFERENCES users(id)      ON DELETE CASCADE,
    CONSTRAINT fk_point_activity FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE,
    CONSTRAINT uq_student_activity_reason UNIQUE (student_id, activity_id, reason)
);

-- =============================================================================
-- 15. ai_documents
-- =============================================================================
CREATE TABLE IF NOT EXISTS ai_documents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by          BIGINT          NOT NULL,
    activity_id         BIGINT          NULL,
    doc_type            doc_type        NULL,
    title               VARCHAR(255)    NULL,
    prompt              TEXT            NOT NULL,
    generated_content   TEXT            NOT NULL,
    model               VARCHAR(100)    NOT NULL DEFAULT 'qwen2.5:7b',
    tokens_input        INTEGER         NULL,
    tokens_output       INTEGER         NULL,
    status              ai_status       NOT NULL DEFAULT 'RAW',
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_user     FOREIGN KEY (created_by)  REFERENCES users(id)      ON DELETE CASCADE,
    CONSTRAINT fk_ai_activity FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE SET NULL
);

-- =============================================================================
-- 16. audit_logs  [Phase 5 — core.AuditLog]
-- =============================================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NULL,
    action          audit_action    NOT NULL,
    object_type     VARCHAR(100)    NOT NULL,
    object_id       VARCHAR(50)     NULL,
    object_repr     VARCHAR(255)    NULL,
    changes         TEXT            NULL,  -- JSON string
    ip_address      INET            NULL,
    timestamp       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_log_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_action    ON audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_logs (timestamp DESC);

-- =============================================================================
-- updated_at Auto-trigger Function
-- =============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach triggers to tables with updated_at
DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'users', 'organizations', 'semesters', 'point_categories',
        'activities', 'budgets', 'tasks',
        'attendance_sessions', 'ai_documents'
    ] LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS trg_%s_updated_at ON %I;
             CREATE TRIGGER trg_%s_updated_at
             BEFORE UPDATE ON %I
             FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();',
            t, t, t, t
        );
    END LOOP;
END $$;


-- =============================================================================
-- 10. activity_participations
-- =============================================================================
CREATE TABLE "activity_participations" (
    "id"                    BIGSERIAL       PRIMARY KEY,
    "activity_id"           BIGINT          NOT NULL,
    "student_id"            BIGINT          NOT NULL,
    "status"                VARCHAR(50)     NOT NULL DEFAULT 'REGISTERED',
    "registered_at"         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "entered_student_code"  VARCHAR(20)     NULL,
    "entered_student_name"  VARCHAR(255)    NULL,
    "attendance_session_id" BIGINT          NULL,
    "checkin_time"          TIMESTAMP       NULL,
    "photo_path"            VARCHAR(500)    NULL,
    "verified_by"           BIGINT          NULL,
    "awarded_points"        DECIMAL(5,2)    NOT NULL DEFAULT 0.00,
    "point_category_id"     BIGINT          NULL,
    "awarded_by"            BIGINT          NULL,
    "awarded_at"            TIMESTAMP       NULL,
    "created_at"            TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"            TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "fk_part_activity" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_part_student"  FOREIGN KEY ("student_id")  REFERENCES "users"("id")      ON DELETE CASCADE,
    CONSTRAINT "fk_part_session"  FOREIGN KEY ("attendance_session_id") REFERENCES "attendance_sessions"("id") ON DELETE SET NULL,
    CONSTRAINT "fk_part_pointcat" FOREIGN KEY ("point_category_id") REFERENCES "point_categories"("id") ON DELETE SET NULL,
    CONSTRAINT "uq_activity_student" UNIQUE ("activity_id", "student_id")
);

