# Generated by Django 6.0.2 on 2026-03-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.BigIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhật ký hệ thống',
                'verbose_name_plural': 'Nhật ký hệ thống',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, choices=[('PLAN', 'Kế hoạch'), ('REPORT', 'Báo cáo'), ('INVITATION', 'Thư mời'), ('OTHER', 'Khác')], max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt', models.TextField()),
                ('generated_content', models.TextField()),
                ('model', models.CharField(default='qwen2.5:7b', max_length=100)),
                ('tokens_input', models.IntegerField(blank=True, null=True)),
                ('tokens_output', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RAW', 'Bản thô AI'), ('DRAFT', 'Bản nháp'), ('EDITED', 'Đã chỉnh sửa'), ('FINAL', 'Bản chính thức')], default='RAW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_documents', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Văn bản AI',
                'verbose_name_plural': 'Văn bản AI',
                'db_table': 'ai_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
