# Generated by Django 6.0.2 on 2026-03-03 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Audit Log (Deprecated)', 'verbose_name_plural': 'AI Audit Logs (Deprecated)'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='ai_audit_logs',
        ),
    ]
