# Generated by Django 6.0.2 on 2026-03-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_phase5_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidocument',
            name='model',
            field=models.CharField(default='qwen2.5:1.5b', max_length=100),
        ),
    ]
