# Generated by Django 6.0.2 on 2026-03-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_update_ai_model_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidocument',
            name='model',
            field=models.CharField(default='qwen2.5-coder:1.5b', max_length=100),
        ),
    ]
