# Generated by Django 6.0.2 on 2026-03-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_alter_aidocument_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
