# Generated by Django 6.0.2 on 2026-03-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_delete_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aidocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Van ban AI', 'verbose_name_plural': 'Van ban AI'},
        ),
        migrations.AddField(
            model_name='aidocument',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async generation tracking', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aidocument',
            name='generation_error',
            field=models.TextField(blank=True, help_text='Error message if generation failed', null=True),
        ),
        migrations.AddField(
            model_name='aidocument',
            name='generation_status',
            field=models.CharField(choices=[('PENDING', 'Dang tao...'), ('DONE', 'Hoan thanh'), ('ERROR', 'Loi')], db_index=True, default='DONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='aidocument',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('PLAN', 'Ke hoach'), ('REPORT', 'Bao cao'), ('INVITATION', 'Thu moi'), ('OTHER', 'Khac')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aidocument',
            name='generated_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aidocument',
            name='status',
            field=models.CharField(choices=[('RAW', 'Ban tho AI'), ('DRAFT', 'Ban nhap'), ('EDITED', 'Da chinh sua'), ('FINAL', 'Ban chinh thuc')], default='RAW', max_length=20),
        ),
    ]
