# Generated by Django 6.0.2 on 2026-03-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_student_code', models.CharField(max_length=20)),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('photo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('VERIFIED', 'Đã xác nhận'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': 'Bản ghi điểm danh',
                'verbose_name_plural': 'Bản ghi điểm danh',
                'db_table': 'attendance_records',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('qr_token', models.CharField(max_length=255, unique=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Đang mở'), ('CLOSED', 'Đã đóng')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phiên điểm danh',
                'verbose_name_plural': 'Phiên điểm danh',
                'db_table': 'attendance_sessions',
            },
        ),
        migrations.CreateModel(
            name='ActivityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Điểm hoạt động',
                'verbose_name_plural': 'Điểm hoạt động',
                'db_table': 'activity_points',
            },
        ),
    ]
