# Generated by Django 6.0.2 on 2026-03-03 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
