# Generated by Django 6.0.2 on 2026-03-04 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_point_category_with_org'),

        ('attendance', '0003_add_activity_and_approved_at_to_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activitypoint',
            name='unique_student_activity_point',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='activity',
        ),
        migrations.AddField(
            model_name='activitypoint',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitypoint',
            name='awarded_by',
            field=models.ForeignKey(blank=True, help_text='Cán bộ đã duyệt và cấp điểm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitypoint',
            name='point_category',
            field=models.ForeignKey(blank=True, help_text='Snapshot danh mục điểm tại thời điểm cấp — không thay đổi dù Activity bị sửa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_points', to='activities.pointcategory'),
        ),
        migrations.AlterField(
            model_name='activitypoint',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_activity_points', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='activitypoint',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='activitypoint',
            constraint=models.UniqueConstraint(fields=('student', 'activity'), name='unique_student_activity_point'),
        ),
    ]
