# Generated by Django 6.0.2 on 2026-03-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_phase1_points_and_schema_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='entered_student_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
