# Generated by Django 6.0.2 on 2026-03-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancerecord_entered_student_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activitypoint',
            name='unique_student_activity_point',
        ),
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_session_student',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='attendance_session',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='verified_by',
        ),
        migrations.DeleteModel(
            name='ActivityPoint',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
